"""i hope everything works

Revision ID: 82ea967de3c5
Revises: 25dd4d6c71d4
Create Date: 2023-02-15 23:32:53.582570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ea967de3c5'
down_revision = '25dd4d6c71d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
