"""please god work i will be a good boy

Revision ID: aed888d7bd08
Revises: 82ea967de3c5
Create Date: 2023-02-15 23:37:23.290588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed888d7bd08'
down_revision = '82ea967de3c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
